services:
  portfolio:
    container_name: portfolio_nextjs
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_WEBSITE_URL: ${NEXT_PUBLIC_WEBSITE_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    restart: always
    ports:
      - 3000:3000